---
ID: "7f42d6b9-acf0-4a0b-88ea-0e5c1633b7c7"
Parent: "f512250b-888a-4716-be2d-c8ef4a5d5eee"
Template: "094eb492-d124-4dfe-9d47-c815f045a316"
Path: /sitecore/content/CodeHat/SXAEnhancement/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
