---
ID: "56dc91df-ff54-4bef-b962-3ad7d3632b04"
Parent: "375a9937-5f37-4fd1-a323-124944544fb0"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/CodeHat/SXAEnhancement/Presentation/Placeholder Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T033920Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
